### ISSUE TITLE
pH Sensor

### ISSUE THREAD

**Issue by gustavo-dg** [iinsouciant/THE-SHRUBBERS#6]
The pH sensor is used to measure the pH the nutrient-rich water in the reservoir. The selected sensor is the [Altas Scientific Gravity pH Sensor/Meter](https://atlas-scientific.com/kits/gravity-analog-ph-kit/). The RPi will supply the sensor with the necessary 5V. The sensor outputs an analog signal, which is not supported by RPi GPIO. The [ADS1015](https://www.adafruit.com/product/1083) analog-to-digital convertor (ADC) will be used to input a readable digital signal to the GPIO pin. I2C will be used to interface the ADC with the RPi and access data from both the pH and EC sensor. Refer to issue #4 for more on I2C.

Atlas Scientific provides a [library in C++](https://www.atlas-scientific.com/files/atlas_gravity.zip) with sample code for using the sensor to determine pH values from a voltage. However, since Python will be utilized, DFRobot also has a [Python library](https://github.com/DFRobot/DFRobot_EC/archive/master.zip) for their sensors, including an analog pH meter similar to the one being used for this project. Using Atlas Scientific's sample code as reference, DFRobot's sample can be modified to work for our sensor.

To read pH values, first create an instance of the pH meter. Then, the calibration process can be initiated with the method `calibration(self, voltage)`. Calibration requires the probe to be placed in buffer solutions, so a user should be able to initiate the process easily via a button/menu selection. See issue #2 and #3 for implementation of user input. Once calibrated, `readPH(self,voltage,temperature)` can be used to get pH values. Note that temperature of the solution is included in the parameters. This value can probably be fixed but might need a temperature sensor to get more accurate readings.

**Comment by iinsouciant** [comment]
implemented with ADC through I2C
